llm:

  provider: gemini
  model:    gemini-2.5-flash
  # model:  gemini-2.5-flash-lite

# youtube:
# 
#   # If you want to use the YouTube Data API in second script
#   use_api: false
#   api_key: ""
#   api_key_env: YT_API_KEY

run:

  debug: true
  use_ytdlp_fallback: true   # use yt-dlp discovery; transcripts via API or yt-dlp
